version: "3"

services:
  front:
    build: ./Dockerfile
    ports:
      - "5173:5173"
    volumes:
     - ./:/home/node/app
     - /home/node/app/node_modules
    tty: true
    stdin_open: true
    command: yarn dev --host
